name: SBOM and Sign

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Syft
        uses: anchore/sbom-action@v0
        id: syft
        with:
          output-file: sbom.spdx.json

      - name: Sign SBOM
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v1.12.1'

      - name: Cosign sbom
        env:
          COSIGN_EXPERIMENTAL: 'true'
        run: |
          cosign attest --predicate sbom.spdx.json --type spdx --yes \
            git+https://github.com/${{ github.repository }}@${{ github.sha }}